### ISSUE TITLE
using the fmiWrapper within a web application

### ISSUE THREAD

**Issue by jtfotso** [Tuebel/FmiWrapper#2]
Hi Tuebel,
I want to use the wrapper within my webApp (ASP.net), but the Instantiate method still Returns Zero.
I thank you for your help.

Jules

**Comment by Tuebel** [comment]
Hi Jules,
sorry for the late reply, I didn't have the time to look into github the last weeks.

The method can return NULL for different reasons:

- no handle could be created for the shared library (common if it is not in the search path of the application. I had a problem once when trying to use relative paths while Debugging from VS). Make sure to use absolute paths to avoid this problem and increase security.
- the fmi2Instatiate method which has been called in the shared library of your fmu returns NULL. Now this can have several reasons which depend on the vendor. Common is that the FmuType or GUID parameters you give the method are wrong. Otherwise there might be an error in the fmu itself.

I advice you to debug the fmi_wrapper.c and have a look at which the function returns NULL.

**Comment by Tuebel** [comment]
I closed this issue due to inactivity.
