### ISSUE TITLE
FMU is not instancing

### ISSUE THREAD

**Issue by bvlassa** [Tuebel/FmiWrapper#6]
Dear,

Below, you can find a piece of code that I use for instancing my models (build by AMESIM).
Why I'm able to load FMU: simple_multiplier3  and is FMU: Linked_Parameter_FMU not loading?

                // Create the instance
                string modelIdentifier = fmd.CoSimulation.modelIdentifier;
                string guid = fmd.guid.ToString();
                Console.WriteLine($"{modelIdentifier} - {guid}");
[Linked_Parameter_FMU.zip](https://github.com/Tuebel/FmiWrapper/files/5678733/Linked_Parameter_FMU.zip)
[simple_multiplier3.zip](https://github.com/Tuebel/FmiWrapper/files/5678734/simple_multiplier3.zip)

                using (var fmu = new FmuInstance(modelIdentifier + ".dll"))
                {
                    // Setup
                    fmu.Log += Fmu_Log;
                    fmu.StepFinished += Fmu_StepFinished;
                    fmu.Instantiate(modelIdentifier + "_Instance", Fmi2Type.fmi2CoSimulation, guid, "", false, true);
                    Console.WriteLine("Types platform: " + fmu.GetTypesPlatform());
                    Console.WriteLine("Version: " + fmu.GetVersion());
                    fmu.SetupExperiment(false, 0, 0, true, 1000);
                    fmu.EnterInitializationMode();
                    fmu.ExitInitializationMode();

                   // Simulate
                    SimulateHEV(fmu);

                    // Terminate the fmu
                    fmu.Terminate();
                }

**Comment by Tuebel** [comment]
Hey, I'm sorry that I let you wait for so long.
Right now I'm running Linux and don't have Visual Studio installed so I can't check your FMUs directly. Do you have any error message? Which line fails?

One issue I frequently ran into were missing dependencies. If your FMU is dynamically linked against another DLL which is not in your system path, instantiating the FMU will fail. I have debugged these cases using the [dependency walker](https://www.dependencywalker.com/). Since the fmu is just a *.zip archive, you can extract the DLLs. Make sure that you match your architecture (x86 or x64).

**Comment by Tuebel** [comment]
Closing it because it is most likely an isssue of the FMU itself.
